name: Codestyle

on:
  push:
    branches:
      - main  # Change this to your main branch name, if different
  pull_request:
    branches:
      - main  # Change this to your main branch name, if different

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint  # Change this to your ESLint command if it's different in your project

      - name: Prettier
        run: npm run check-format
